server:
  port: 8766

spring:
  application:
    name: could-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul: 
  routes:
    ribbon: 
      path: /ribbon/**
      serviceId: client-ribbon
    feign: 
      path: /feign/**
      serviceId: client-feign